packages:
  - apps/*
  - packages/*

overrides:
  esbuild: 0.28.1
  ws: 8.21.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - vue-demi
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
