// Self-hosts the Scalar standalone bundle so the /docs page loads it from our
// own origin instead of jsDelivr (avoids a third-party CDN dependency and lets
// a strict CSP stay closed). Runs before every build/deploy/dev.
//
// The installed @scalar/api-reference version is the single source of truth:
// the bundle is copied to a version-stamped filename (long-cache safe) and the
// matching URL is written into src/scalar-asset.ts, so the code always points
// at exactly the file that was copied -- no drift, no hand-edited version.
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const apiDir = dirname(dirname(fileURLToPath(import.meta.url)));

// Resolve the package root from its main entry (exports maps block deep paths).
let pkgRoot = dirname(require.resolve("@scalar/api-reference"));
while (!existsSync(join(pkgRoot, "package.json"))) pkgRoot = dirname(pkgRoot);
const pkg = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8"));

const source = join(pkgRoot, pkg.browser);
if (!existsSync(source)) {
	throw new Error(`Scalar standalone bundle not found at ${source} (pkg.browser=${pkg.browser})`);
}

const assetsDir = join(apiDir, "public", "assets");
mkdirSync(assetsDir, { recursive: true });
for (const file of readdirSync(assetsDir)) {
	if (/^scalar-.*\.js$/.test(file)) rmSync(join(assetsDir, file));
}

const filename = `scalar-${pkg.version}.js`;
copyFileSync(source, join(assetsDir, filename));

const url = `/assets/${filename}`;
const module = [
	"// GENERATED by scripts/copy-scalar.mjs -- do not edit.",
	"// URL of the self-hosted Scalar standalone bundle served from public/assets.",
	`export const SCALAR_CDN_URL = ${JSON.stringify(url)};`,
	"",
].join("\n");
const modulePath = join(apiDir, "src", "scalar-asset.ts");
if (!existsSync(modulePath) || readFileSync(modulePath, "utf8") !== module) {
	writeFileSync(modulePath, module);
}

console.log(`[copy-scalar] ${pkg.name}@${pkg.version} -> public${url}`);
